<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>228edd82-8dfc-4af0-9c4b-7744fe3b1647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.close-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layoutMain']/div/app-home/div/div[3]/p-dialog/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;×&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b8bc140b-9340-4003-9796-42f6a58f3812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>d8ad894e-09c9-49fa-9a7b-1bf705353bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> × </value>
      <webElementGuid>12d40752-e496-456b-8c43-d02b7f0e59ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutMain&quot;)/div[@class=&quot;bfc-right-wrap&quot;]/app-home[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;card flex justify-content-center banner&quot;]/p-dialog[@class=&quot;p-element ng-tns-c3229452358-1 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c3229452358-1 p-dialog-mask p-component-overlay p-component-overlay-enter p-dialog-mask-scrollblocker ng-star-inserted&quot;]/div[@class=&quot;p-element ng-trigger ng-trigger-animation ng-tns-c3229452358-1 p-dialog p-component ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c3229452358-1 p-dialog-content&quot;]/div[@class=&quot;close-icon-container ng-tns-c3229452358-1&quot;]/button[@class=&quot;close-btn&quot;]</value>
      <webElementGuid>b264f489-d576-4788-b112-aa4d334fd9fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutMain']/div/app-home/div/div[3]/p-dialog/div/div/div/div/button</value>
      <webElementGuid>c5ba78bc-c1b5-4d70-bce7-d482fb1bd2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Star Employees'])[1]/following::button[2]</value>
      <webElementGuid>1d0e1b96-0e4f-4b00-a16d-427851269b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Senior Technical Specialist'])[2]/following::button[11]</value>
      <webElementGuid>18b05d12-5726-4abd-ae1a-ad25484f1e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>ad0f29ce-8b10-4a05-b5fd-2dd0c372d851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p-dialog/div/div/div/div/button</value>
      <webElementGuid>dd0a8078-0053-4a3a-8f11-6352e44c6a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' × ' or . = ' × ')]</value>
      <webElementGuid>a4dea4cb-8815-4fff-b314-581078aa5c6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
