<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Password_fa eye-icon fa-eye-slash</name>
   <tag></tag>
   <elementGuidId>f1920f76-28af-48bf-947c-27bfe953c64c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.eye-icon.fa-eye-slash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layoutMain']/div/app-login-custom/section/div[3]/div/div[2]/div/div/form/div[2]/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>420d6ed6-2059-4775-a912-79655a542aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa eye-icon fa-eye-slash</value>
      <webElementGuid>bbd662d1-c9c9-40b1-9312-67e53d144296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layoutMain&quot;)/div[1]/app-login-custom[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;sectionPadding mainContainer&quot;]/div[@class=&quot;container form-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-md-6 col-sm-12&quot;]/div[@class=&quot;card-style&quot;]/div[@class=&quot;login-form&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;input-group&quot;]/span[1]/i[@class=&quot;fa eye-icon fa-eye-slash&quot;]</value>
      <webElementGuid>8ba5bb92-55a1-4251-bc39-f8aabf8a8806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutMain']/div/app-login-custom/section/div[3]/div/div[2]/div/div/form/div[2]/div/span/i</value>
      <webElementGuid>2a126657-8b4e-4bc8-9235-8c7b35841868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>9fd010e7-b504-4344-8a08-cb4453577d2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
