<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Policies  Forms_myIframe</name>
   <tag></tag>
   <elementGuidId>3d9848af-299f-4223-95e2-079c3a06a611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myIframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='myIframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#myIframe</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b2f2c99e-9d06-441e-b5a2-c89ab4cb7ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myIframe</value>
      <webElementGuid>8171987c-1b61-4922-8b11-dd349592979e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c67bee95-2263-471b-a98a-0e743daa4e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>700px</value>
      <webElementGuid>495dd002-92f3-4f1f-995b-4fd7df2206c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://oldportal.damcogroup.com:8090/DAMCO_PORTAL_DOTNET/NavigateToASPfromNBM.aspx?Url=damco_policy.asp</value>
      <webElementGuid>3f9ae29e-a0ac-434c-8955-770538c52971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myIframe&quot;)</value>
      <webElementGuid>92399414-5735-4e0c-af8c-0556f92c52ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='myIframe']</value>
      <webElementGuid>5badc7e1-9380-4300-9bcd-9b2d0785a794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layoutMain']/div/app-canvass/div/div/div/iframe</value>
      <webElementGuid>6803fabd-5b65-43fb-8552-259391f37d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>28be970b-0db2-482f-a94c-5417d7cc1556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'myIframe' and @src = 'https://oldportal.damcogroup.com:8090/DAMCO_PORTAL_DOTNET/NavigateToASPfromNBM.aspx?Url=damco_policy.asp']</value>
      <webElementGuid>7dd4236a-96a6-47b6-b66d-4d559706a26d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
